accounts:
  - name: joe
    coins: ["20000token", "200000000stake"]
  - name: mario
    coins: ["20000token", "200000000stake"]
  - name: sadun
    coins: ["20000token", "200000000stake"]
  - name: andy
    coins: ["20000token", "200000000stake"]
  - name: christian
    coins: ["20000token", "200000000stake"]
  - name: sarah
    coins: ["20000token", "200000000stake"]
  - name: cam
    coins: ["20000token", "200000000stake"]
  - name: ash
    coins: ["20000token", "200000000stake"]
validator:
  name: joe
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
# faucet:
#   name: bob
#   coins: ["5token", "100000stake"]
