version: "3"

services:
  voterdnode0:
    container_name: voterdnode0
    image: "voterapp"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-voterd.log}
    volumes:
      - ./build:/voterd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  voterdnode1:
    container_name: voterdnode1
    image: "voterapp"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-voterd.log}
    volumes:
      - ./build:/voterd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  voterdnode2:
    container_name: voterdnode2
    image: "voterapp"
    environment:
      - ID=2
      - LOG=${LOG:-voterd.log}
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      - ./build:/voterd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  voterdnode3:
    container_name: voterdnode3
    image: "voterapp"
    environment:
      - ID=3
      - LOG=${LOG:-voterd.log}
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      - ./build:/voterd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
